# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesSet',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionSet', models.TextField()),
                ('questionTimeStamp', models.DateTimeField()),
            ],
        ),
    ]
