# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255, unique=True)),
                ('EmailID', models.EmailField(max_length=254)),
                ('Age', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('Password', models.CharField(max_length=255)),
                ('UserScore', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
