# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='UserScore',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
