# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usermodel_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='UserName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
