# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170404_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('NumGamePlayed', models.IntegerField(blank=True, null=True)),
                ('TotalScore', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['UserScore']},
        ),
        migrations.AddField(
            model_name='userstat',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserModel'),
        ),
    ]
