# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170402_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='UserScore',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
