# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-08 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170407_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['-UserScore']},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='UserFriends',
            field=models.ManyToManyField(to='login.UserModel'),
        ),
    ]
