# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170408_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='UserFriends',
            field=models.ManyToManyField(blank=True, null=True, to='login.UserModel'),
        ),
    ]
