# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPassword',
            fields=[
                ('apiID', models.AutoField(primary_key=True, serialize=False)),
                ('apiName', models.TextField()),
                ('apiPassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuesSet_v2',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionDate', models.DateTimeField()),
                ('questionSet', models.TextField()),
                ('questionTimeStamp', models.IntegerField()),
                ('questionEndStamp', models.IntegerField()),
                ('questionBoutEndStamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rankingSet',
            fields=[
                ('resultNumber', models.AutoField(primary_key=True, serialize=False)),
                ('questionID', models.IntegerField()),
                ('userName', models.CharField(max_length=255)),
                ('userScore', models.FloatField()),
                ('correctans', models.IntegerField(blank=True, null=True)),
                ('wrongans', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Top10Model',
            fields=[
                ('rID', models.AutoField(primary_key=True, serialize=False)),
                ('questionID', models.IntegerField()),
                ('top10User', models.TextField()),
            ],
        ),
    ]
