# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuesSet',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionSet', models.TextField()),
                ('questionTimeStamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='QuesSet_v1',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionSet', models.TextField()),
                ('questionTimeStamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuesSet_v2',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionDate', models.CharField(max_length=255)),
                ('questionSet', models.TextField()),
                ('questionTimeStamp', models.IntegerField()),
                ('questionEndStamp', models.IntegerField()),
                ('questionBoutEndStamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rankingSet',
            fields=[
                ('resultNumber', models.AutoField(primary_key=True, serialize=False)),
                ('questionA', models.IntegerField()),
                ('userName', models.CharField(max_length=255)),
                ('userScore', models.FloatField()),
            ],
        ),
    ]
