# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesset',
            name='questionTimeStamp',
            field=models.IntegerField(),
        ),
    ]
