# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuesSet',
        ),
        migrations.DeleteModel(
            name='QuesSet_v1',
        ),
        migrations.AlterField(
            model_name='quesset_v2',
            name='questionDate',
            field=models.DateTimeField(),
        ),
    ]
