# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0002_auto_20170330_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPassword',
            fields=[
                ('apiID', models.AutoField(primary_key=True, serialize=False)),
                ('apiName', models.TextField()),
                ('apiPassword', models.TextField()),
            ],
        ),
    ]
