# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0003_apipassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top10Model',
            fields=[
                ('rID', models.AutoField(primary_key=True, serialize=False)),
                ('questionID', models.IntegerField()),
                ('top10User', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='rankingset',
            old_name='questionA',
            new_name='questionID',
        ),
    ]
