# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0003_auto_20170326_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesSet_v1',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('questionSet', models.TextField()),
                ('questionTimeStamp', models.IntegerField()),
            ],
        ),
    ]
