# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0004_quesset_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='rankingSet',
            fields=[
                ('resultNumber', models.AutoField(primary_key=True, serialize=False)),
                ('questionA', models.IntegerField()),
                ('userName', models.CharField(max_length=255)),
                ('userScore', models.FloatField()),
            ],
        ),
    ]
