# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0004_auto_20170401_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingset',
            name='correctans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rankingset',
            name='wrongans',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
