# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0006_quesset_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesset_v2',
            name='questionDate',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 18, 33, 31, 78156)),
            preserve_default=False,
        ),
    ]
