# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0007_quesset_v2_questiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesset_v2',
            name='questionBoutEndStamp',
            field=models.IntegerField(default=1490725800),
            preserve_default=False,
        ),
    ]
