# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genQues', '0008_quesset_v2_questionboutendstamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesset_v2',
            name='questionDate',
            field=models.CharField(max_length=255),
        ),
    ]
