# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='EmailID',
            field=models.EmailField(default='prakhar@schooglink.com', max_length=254),
            preserve_default=False,
        ),
    ]
